require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 15

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/concerns/default_endpoint.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/concerns/default_endpoint.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/concerns/default_endpoint.rb'

