require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 15

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'app/admin/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/pages/**/*'
