---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/session":
    post:
      summary: Create session
      tags:
      - Sessions
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: Session is created
        '404':
          description: Not found
        '401':
          description: Invalid credentials
        '422':
          description: Blank username and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - username
              - password
              properties:
                username:
                  type: string
                  example: montexx
                password:
                  type: string
                  example: qwerty12
    delete:
      summary: Destroys session
      tags:
      - Sessions
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        description: Access token
        schema:
          type: string
      responses:
        '204':
          description: Session is destroyed
        '401':
          description: Invalid token
  "/api/v1/user":
    post:
      summary: Create user
      tags:
      - User
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: Created
        '422':
          description: Invalid params
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - user
              properties:
                user:
                  type: object
                  required:
                  - username
                  - password
                  - password_confirmation
                  properties:
                    username:
                      type: string
                      example: kindra.framixx
                    password:
                      type: string
                      example: qwerty12
                    password_confirmation:
                      type: string
                      example: qwerty12
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
